[package]
name = "brainfuck-compilers"
version = "0.1.0"
authors = ["pretzelhammer <7769424+pretzelhammer@users.noreply.github.com>"]
edition = "2018"

[[bin]]
name = "bf_interpreter"
path = "src/bf_interpreter.rs"

[[bin]]
name = "bf_to_x86_64_compiler"
path = "src/bf_to_x86_64_compiler.rs"
